# Generated by Django 5.2.4 on 2025-09-01 15:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_rtchat', '0002_alter_chatmessage_group'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='chatgroup',
            name='user_online',
            field=models.ManyToManyField(blank=True, related_name='online_in_group', to=settings.AUTH_USER_MODEL),
        ),
    ]
